### ISSUE TITLE
[BUG] The problem with the /premium command

### ISSUE THREAD

**Issue by TheDamStex** [Elytrium/LimboAuth#85] opened 2023-03-04 00:08 UTC
[02:56:59 INFO]: [connected player] TheDamStex21 (/) has disconnected: LimboAuth >>
Учетная запись синхронизирована с Microsoft.net
[02:56:59 INFO]: [server connection] TheDamStex21 -> vanilla has disconnected
[02:57:14 ERROR]: [initial connection] /: exception encountered in net.elytrium.limboapi.server.LimboSessionHandlerImpl@2ae8bc7a
java.lang.IllegalArgumentException: must provide non-null, non-empty hash
        at net.elytrium.limboauth.thirdparty.at.favre.lib.crypto.bcrypt.BCryptParser$Default.parse(BCryptParser.java:53) ~[?:?]
        at net.elytrium.limboauth.thirdparty.at.favre.lib.crypto.bcrypt.BCrypt$Verifyer.innerVerifyBytes(BCrypt.java:544) ~[?:?]
        at net.elytrium.limboauth.thirdparty.at.favre.lib.crypto.bcrypt.BCrypt$Verifyer.verify(BCrypt.java:432) ~[?:?]
        at net.elytrium.limboauth.handler.AuthSessionHandler.checkPassword(AuthSessionHandler.java:521) ~[?:?]
        at net.elytrium.limboauth.handler.AuthSessionHandler.onChat(AuthSessionHandler.java:238) ~[?:?]
        at net.elytrium.limboapi.server.LimboSessionHandlerImpl.handleChat(LimboSessionHandlerImpl.java:227) ~[?:?]
        at net.elytrium.limboapi.server.LimboSessionHandlerImpl.handle(LimboSessionHandlerImpl.java:209) ~[?:?]
        at com.velocitypowered.proxy.protocol.packet.chat.keyed.KeyedPlayerCommand.handle(KeyedPlayerCommand.java:191) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:143) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:92) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:57:14 INFO]: [initial connection] / has disconnected

The problem with the /premium command is that when you use it, you get kicked out of the server and it says that your account has been synchronized with Microsoft. When you try to log back into the server, it asks for your password, but when you enter it, you get kicked out again and an error message appears in the console.

**Comment by hevav** [comment] 2023-03-04 05:57
Duplicate of #84

**Closed** 2023-03-04 05:58 UTC
Labels: bug
