### ISSUE TITLE
[BUG] неработает LimboAuth / doesnt work LimboAuth

### ISSUE THREAD

**Issue by DanyaSahor** [Elytrium/LimboAuth#147] opened 2024-02-13 13:35 UTC
Версия velocity/velocity version: velocity 3.3.0 snapshot build #358
Версия LimboAPI/LimboAPI version: 1.1.21

[14:11:44 ERROR]: Couldn't pass ProxyInitializeEvent to limboauth
java.lang.NoClassDefFoundError: com/velocitypowered/proxy/protocol/packet/ServerLogin
        at net.elytrium.limboauth.listener.AuthListener.<clinit>(AuthListener.java:176) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:387) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.onProxyInitialization(LimboAuth.java:208) ~[?:?]
        at net.elytrium.limboauth.Lmbda$3.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[Velocity.jar:3.3.0-SNAPSHOT (git-ef861819-b358)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[Velocity.jar:3.3.0-SNAPSHOT (git-ef861819-b358)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[Velocity.jar:3.3.0-SNAPSHOT (git-ef861819-b358)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: com.velocitypowered.proxy.protocol.packet.ServerLogin
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[Velocity.jar:3.3.0-SNAPSHOT (git-ef861819-b358)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[Velocity.jar:3.3.0-SNAPSHOT (git-ef861819-b358)]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 10 more

**Comment by UserNugget** [comment] 2024-02-13 13:38
Duplicate of https://github.com/Elytrium/LimboAuth/issues/140

**Closed by UserNugget** 2024-02-13 13:38 UTC
Labels: bug
