### ISSUE TITLE
Do not remove premium account passwords from database

### ISSUE THREAD

**Issue by MegalithOffical** [Elytrium/LimboAuth#39] opened 2022-06-24 19:02 UTC
Hello i use MYSQL database and my Site also connected to same database when my players use /premium command the plugin delete's password from database thats why my players couldnt login from site. how can i fix that ?

**Comment by ArtifactyNight** [comment] 2022-06-27 06:26
Same issue here
It's have problem with my webshop

**Comment by moderator10000078** [comment] 2022-06-27 08:16
I think it's worth writing to the developer so that he adds a function to the config that does not delete the password from the database when enabled /premium

**Comment by SenPr** [comment] 2022-06-27 15:14
this honestly shouldn't be to hard to change. If you're willing to compile the plugin yourself

**Comment by TheSidOffical** [comment] 2022-06-27 16:23
moderator10000078, you are right there should be more Options about Database utilitys and settings.

**Comment by hevav** [comment] 2022-12-25 19:07
Duplicate of #23

**Closed by hevav** 2022-12-25 19:07 UTC
Labels: enhancement
